### ISSUE TITLE
Objective Tracker Module Return

### ISSUE THREAD

**Issue by Wutname1** [Wutname1/SpartanUI#527]
Objective Tracker was depreciated in DF. Let's bring it back but with my original vision this time.

- [ ] Auto Collapse based on rules
- [ ] Auto Collapse specific sections based on rules
- [ ] Text updates
- [ ] Background/Border?
  - [ ] Background/Border on mouseover, help with readability.
- [ ] Cleanup borders and textures
